### ISSUE TITLE
Size on Android Opera

### ISSUE THREAD

**Issue by darktweek** [manilarome/the-glorious-startpage#3]
Hi!
I have host your project on my little server.
I have try on Opera on windows and Linux it's  work very well.
For Android there's a problem on size with the top and bottom icon.
![Screenshot_20200527-082114](https://user-images.githubusercontent.com/12700953/82985075-a9a12100-9ff3-11ea-8e01-1246d9b2bade.png)

**Comment by manilarome** [comment]
>  I have host your project on my little server.
I have try on Opera on windows and Linux it's work very well.

Nice! Glad you like it. :)

>  For Android there's a problem on size with the top and bottom icon.

I'm aware of this. When I started this project 4 days ago, I don't plan to support android because this is just a pastime of mine. But yeah, I've changed my mind. Maybe I'll try to use bootstrap or something. It's been ages since I wrote a webpage.

**Comment by darktweek** [comment]
Yes your project enjoy my day 😁.
I will wait for this.

And, could you add a way to edit/change the shortcut at the bottom?

**Comment by manilarome** [comment]
> And, could you add a way to edit/change the shortcut at the bottom?

Yeah, I'll create a code in javascript that will make the configuration
easier. Our problem right now is it is my first time to write one si
there's a learning curve. Maybe in a week or two. Anyway, please don't
close this issue yet.

**Comment by darktweek** [comment]
I will wait no worries.
It's a great job for now!
Good learning!

**Comment by manilarome** [comment]
Hey closing this now, smartphone support has been implemented! :) Thanks!
